name: VeldoriaCore
version: 1.4
main: ru.veldoria.core.VeldoriaCore
api-version: 1.21
softdepend: [AuraSkills, WorldGuard, Towny]
commands:
  veldoriacore:
    description: Основная команда плагина
    permission: veldoria.admin
    usage: /veldoriacore give <item>