name: VeldoriaCore
version: 1.7
main: ru.veldoria.core.VeldoriaCore
api-version: 1.21
softdepend: [AuraSkills, WorldGuard, Towny, PlayerPoints]
commands:
  veldoriacore:
    description: Админ-команда
    permission: veldoria.admin
    usage: /veldoriacore give <item>
  disenchant:
    description: Открыть стол снятия чар
    usage: /disenchant
    aliases: [disenchanter, disen]
  prestige:
    description: Открыть меню престижа
    usage: /prestige